In [1]:
import numpy as np


In [7]:
a=np.linspace(0,5,4)
a

array([0.        , 1.66666667, 3.33333333, 5.        ])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.fives(3)

AttributeError: module 'numpy' has no attribute 'fives'

In [18]:
c=np.eye(3)

c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
d=np.eye(3,2)
d

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [22]:
d=np.diag([7,9,3,4])
d

array([[7, 0, 0, 0],
       [0, 9, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [24]:
np.diag(d)# to found the diagonal elements


array([7, 9, 3, 4])

In [26]:
random_array=np.random.randint(4,5,6)
random_array

array([4, 4, 4, 4, 4, 4])

In [29]:
random_array=np.random.randint(4)
random_array

2

In [31]:
random_array=np.random.randn(100)
random_array

array([-6.71814608e-01,  2.02251673e+00,  4.37130847e-02,  6.96053106e-01,
       -5.60300943e-01, -3.27012745e-01,  5.71327022e-01, -3.24356546e-02,
       -6.05854590e-01,  9.15300018e-01,  2.86203073e-01,  7.06309995e-01,
       -9.15961854e-01, -4.13325922e-03, -2.21549775e+00, -6.78305721e-01,
       -1.15053939e+00,  5.23995764e-01,  6.43293449e-01, -1.81707926e+00,
        1.05346849e+00,  1.72996202e+00, -1.09095759e+00,  5.90351020e-01,
        1.53312932e-01, -2.05500547e+00,  3.39524149e-01,  2.78902806e-01,
        4.12411991e-01, -6.10362767e-01,  7.92928563e-01,  1.91682162e+00,
        1.66088659e+00,  1.55102354e-01,  1.91706956e-02, -1.27350344e+00,
        3.89995111e-01,  4.82984764e-02, -3.27443888e-01,  9.94380376e-01,
        1.73016565e+00,  2.12140246e-01,  7.26781729e-01, -6.62140590e-01,
       -2.17862559e+00,  1.19160703e+00,  6.54439234e-01,  8.00311594e-01,
        4.19295375e-01, -2.72491270e-01, -7.56658477e-01, -3.99454282e-01,
       -5.43280566e-01, -

In [33]:
d=np.array([2,5,8,7],[3,1,9,0])
d

TypeError: Field elements must be 2- or 3-tuples, got '3'

In [1]:
n=[3,4,6,7,8]
n

[3, 4, 6, 7, 8]

In [2]:
print(type(n))

<class 'list'>


In [5]:
import numpy as np

In [6]:
Numpy=np.array(n)

In [7]:
print(Numpy)

[3 4 6 7 8]


In [8]:
type(Numpy)

numpy.ndarray

In [10]:
L=range(5000)
%timeit [i**2 for i in L]

695 µs ± 43.6 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [11]:
a=np.arange(5000)
%timeit a**2

6.77 µs ± 183 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# Creating array(Manually creating arrays)

In [12]:
#1-D
b= np.array([0,1,2,3])
b

array([0, 1, 2, 3])

In [13]:
#print dimensions
b.ndim

1

In [14]:
#shape
b.shape

(4,)

In [15]:
#2-D
b=np.array([[0,1,2],[3,4,5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
b.ndim

2

In [17]:
b.shape

(2, 3)

In [18]:
#3D
c=np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [19]:
c.ndim

3

In [20]:
c.shape

(2, 2, 2)

# Creating Numpy Array from a list

In [21]:
# we know how to create a list,right
m_list=[2,3,4]
m_list


[2, 3, 4]

In [22]:
np.array(m_list)

array([2, 3, 4])

In [26]:
#we can convert a matrix which is also a list to array
my_matrix=[[4,5,6],[7,8,9],[9,8,4]]
my_matrix

[[4, 5, 6], [7, 8, 9], [9, 8, 4]]

In [27]:
np.array(my_matrix)

array([[4, 5, 6],
       [7, 8, 9],
       [9, 8, 4]])

In [28]:
np.array(my_matrix).shape

(3, 3)

### functions for creating arrays

#### arange

In [2]:
import numpy as np
n=np.arange(10)
n

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
p=np.arange(1,20,2)
p

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

### Linscape

In [6]:
#return evenly spaced numbers over a specified interval.
d=np.linspace(0,5,6)
d

array([0., 1., 2., 3., 4., 5.])

In [7]:
v=np.linspace(0,5,3)
v

array([0. , 2.5, 5. ])

In [9]:
# i want to get 3 evenly spaced points between 0 to 10
np.linspace(0,10,7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

### zeros and ones
#### Generated arrays of zeros or ones

In [11]:
 np.zeros(4)

array([0., 0., 0., 0.])

In [12]:
b=np.zeros((4,4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
a=np.ones((4,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Creates a identity matrix
###### .An indentity matrix if you are not familier is used in linier algebra problems and is a two dimensional squared matrix means number of rows are same as column with diagonals of ones and everything is zero

In [15]:
n=np.eye(3)
n

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
s=np.eye(3,4)
s

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [19]:
#create array using diag function
a=np.diag([3,4,6,9])
a

array([[3, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 9]])

In [20]:
np.diag(a)

array([3, 4, 6, 9])

In [21]:
a

array([[3, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 9]])

##### Random -->Numpy also has lots of ways to create random number arrays:

In [22]:
aaa=np.random.randint(1,222,8)
aaa

array([177,  89,  60,  34,  66,  93,  28, 208])

In [23]:
bbb=np.random.rand(4)
bbb

array([0.97290417, 0.66088102, 0.69867518, 0.17641656])

In [24]:
a=np.random.randn(50)
a

array([-1.52615719,  1.10515227, -0.2356525 ,  1.51479142,  0.49320966,
       -0.82798279, -0.22812958,  0.35609549, -0.68002082, -1.14657555,
        0.53408804, -1.10388922,  1.2572465 ,  0.60029155, -0.00990781,
        1.00354609, -1.01562307, -0.31581619, -0.95555788,  1.91250522,
        0.99819986,  0.11627035,  1.27649007,  1.57100436, -1.67416455,
        0.62413875, -0.5715789 , -1.04080356, -0.65165128,  0.51688699,
       -0.67864608,  1.24496254,  1.17256176,  0.22246196, -0.65529413,
        0.4439679 , -0.73358414, -1.95159853,  2.25944613,  0.81412665,
       -0.42080379, -0.38799885, -0.13488276, -0.49032841,  0.83007706,
       -0.69419733, -0.54229288,  0.50452131, -0.68883299, -0.55666155])

In [25]:
#copy array
a=np.array([4,5,6])
b=a
b[0]=102
print(a)
print(b)

[102   5   6]
[102   5   6]


In [5]:
arr=np.arange(25)
print(arr)
print(arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
(25,)


In [6]:
import numpy as np
a1=arr.reshape(5,5)
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [7]:
a=np.array([[4,7,8],[7,8,4]])
print(a)
print("shape of a:{}".format(a.shape))

[[4 7 8]
 [7 8 4]]
shape of a:(2, 3)


In [8]:
# reshaping 
b=a.reshape(3,2)
print(b)
print("shape of b:{}".format(b.shape))

[[4 7]
 [8 7]
 [8 4]]
shape of b:(3, 2)


In [10]:
#Transpose array
a=np.array([[3,4,5],[6,7,8]])
print("shape:{}".format(a.shape))
print(a)

shape:(2, 3)
[[3 4 5]
 [6 7 8]]


In [11]:
s=a.T
print(s)

[[3 6]
 [4 7]
 [5 8]]


In [12]:
a=np.array([[1,2,3],[4,6,7]])
a.ravel()


array([1, 2, 3, 4, 6, 7])

In [14]:
s.ravel()

array([3, 6, 4, 7, 5, 8])

In [17]:
#sorting
a=np.array([[5,6,3],[22,4,56,]])
b=np.sort(a,axis=1)
b

array([[ 3,  5,  6],
       [ 4, 22, 56]])

In [18]:
a=np.array([[5,6,3],[22,4,56,]])
b=np.sort(a,axis=0)
b

array([[ 5,  4,  3],
       [22,  6, 56]])

In [19]:
#Add/Remove operation on numpy array
a=np.array([5,6,7])
a=np.append(a,[3,6,8])
print("numpy array after addition:",a)

numpy array after addition: [5 6 7 3 6 8]


In [20]:
a=np.delete(a,2)
print("numpy array after deletion of one element:",a)

numpy array after deletion of one element: [5 6 3 6 8]


In [21]:
#Indexing
a=np.arange(3,10)
print(a)
print(a[5])

[3 4 5 6 7 8 9]
8


In [22]:
a=np.diag([1,3,5])
print(a)
print(a[2,1])

[[1 0 0]
 [0 3 0]
 [0 0 5]]
0


In [23]:
a[2,1]=5
a

array([[1, 0, 0],
       [0, 3, 0],
       [0, 5, 5]])

### slicing

In [24]:
a=np.arange(4,15)
a

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
a[1:7:2]

array([5, 7, 9])

In [26]:
a=np.arange(10)
a[5:]=10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [28]:
b=np.arange(5)
b

array([0, 1, 2, 3, 4])

In [29]:
b[::-1]

array([4, 3, 2, 1, 0])

In [31]:
a[5:]=b[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

## Fancy Indexing


In [32]:
a=np.random.randint(0,20,5)
a

array([18, 15, 18, 18, 11])

In [33]:
a[a%2==0]

array([18, 18, 18])

In [34]:
a[a%2==0]=-1
a

array([-1, 15, -1, -1, 11])

#### indexing with an array of integers


In [36]:
a=np.arange(0,111,10)
a

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110])

In [39]:
a[[2,3,7,5,6]]     #doubt

array([20, 30, 70, 50, 60])

In [40]:
a[[6,3]]=-100   #doubt
a

array([   0,   10,   20, -100,   40,   50, -100,   70,   80,   90,  100,
        110])

#### Operations

In [2]:
import numpy as np
s=np.array([3,4,6,8])
print(s)
print(s+1)

[3 4 6 8]
[4 5 7 9]


In [3]:
s**2

array([ 9, 16, 36, 64])

In [6]:
b=np.ones(4)+1
b

array([2., 2., 2., 2.])

In [7]:
s-b

array([1., 2., 4., 6.])

In [8]:
s*b

array([ 6.,  8., 12., 16.])

In [10]:
a=np.array([[1,2],[3,4],[5,6]])
b=np.array([[4,4],[4,4],[4,4]])
print("sum of a and b:\n",a+b)
print("sum of a and b:\n",a*b)

sum of a and b:
 [[ 5  6]
 [ 7  8]
 [ 9 10]]
sum of a and b:
 [[ 4  8]
 [12 16]
 [20 24]]


In [13]:
a=np.array([1,2,3,4])
b=np.array([5,3,2,4])
print(a==b)
print(a>b)

[False False False  True]
[False False  True False]


In [29]:
s=np.array([1.5,1,0,0],dtype=bool)
t=np.array([1,0,1,0],dtype=bool)
# np.logical_or(s,t)
s+t

array([ True,  True,  True, False])

In [28]:
s=np.array([1,1,0,0],dtype=int)
t=np.array([1,0,1,0],dtype=int)
np.logical_or(s,t)

array([ True,  True,  True, False])

In [19]:
s+t

array([2, 1, 1, 0])

In [27]:
s=np.array([1.5,5,2,5],dtype=int)
t=np.array([1.6,2,1,3],dtype=int)
np.logical_or(s,t)
s+t

array([2, 7, 3, 8])

In [31]:
a=([1,2,3],[6,7,8])
b=([1,2],[6,7,7])
print(np.matmul(a,b))

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [2]:
import numpy as np
d=np.diag([3,4,7,8])
print(d*d)

[[ 9  0  0  0]
 [ 0 16  0  0]
 [ 0  0 49  0]
 [ 0  0  0 64]]


In [3]:
#matrix multiplication
a=np.array([[2,3,6],[6,7,8],[3,4,1]])
b=np.array([[2,6,6],[6,2,8],[3,7,1]])
print("matrix multiplication:\n",np.matmul(a,b))


matrix multiplication:
 [[ 40  60  42]
 [ 78 106 100]
 [ 33  33  51]]


### Transcendental function:

In [5]:
a=np.arange(4)
np.sin(a)

array([0.        , 0.84147098, 0.90929743, 0.14112001])

In [6]:
np.log(a)

C:\Users\91934\AppData\Local\Temp\ipykernel_4652\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229])

In [7]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

### Basic reduction

In [8]:
y=np.array([1,4,6,7])
np.sum(y)

18

In [9]:
v=np.array([[3,4],[5,7]])
v

array([[3, 4],
       [5, 7]])

In [10]:
v.sum(axis=0)

array([ 8, 11])

In [11]:
v.sum(axis=1)

array([ 7, 12])

In [12]:
y.min()

1

In [13]:
y.max()

7

In [14]:
y.argmin()

0

In [15]:
y.argmax()

3

In [16]:
np.mean(y)

4.5

In [17]:
np.median(y)

5.0

In [18]:
np.std(y)

2.29128784747792